AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Environment:
    Type: String
    AllowedValues:
      - development
      - production
      - staging
      - testing

  ServerClusterRoleArn:
    Type: String


Resources:

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Environment}-style-transfer-images
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [PUT, GET]
            AllowedOrigins: ['*']
            MaxAge: 3600
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  ImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Statement:
          - Sid: ServerInputReadWrite
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - !Sub ${ImageBucket.Arn}/private/input/*
              - !Sub ${ImageBucket.Arn}/public/input/*
            Principal:
              AWS: !Ref ServerClusterRoleArn
          - Sid: PublicRead
            Effect: Allow
            Action: s3:GetObject
            Resource: !Sub ${ImageBucket.Arn}/public/*
            Principal: '*'
