AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Environment:
    Type: String
    AllowedValues:
      - development
      - production
      - staging
      - testing


Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Environment}-style-transfer-images
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [PUT, GET]
            AllowedOrigins: ['*']
            MaxAge: 3600
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Action: s3:GetObject
            Resource:
              - !Sub ${S3Bucket.Arn}/public/*
              - !Sub ${S3Bucket.Arn}/style/*
            Principal: '*'


Outputs:

  S3BucketName:
    Value: !Ref S3Bucket

  S3BucketUrl:
    Value: !Sub https://${S3Bucket.DomainName}
