version: '2.4'

services:
  server:
    image: node:10.15.0
    container_name: neural-style-transfer-server
    environment:
      PORT: 3000
    env_file:
      - ./server/resources.env
    volumes:
      - ./server:/app
      - ${HOME}/.aws:/home/node/.aws
    ports:
      - 3000:3000
    working_dir: /app
    user: node
    command: [npm, run, dev]

  client:
    image: node:10.15.0
    volumes:
      - ./client:/app
    ports:
      - 8080:8080
    working_dir: /app
    command: [npm, run, dev]

  agent:
    build:
      context: agent
      dockerfile: dev.Dockerfile
    image: sjawhar/neural-style-transfer-agent-dev
    container_name: neural-style-transfer-agent
    env_file:
      - ./agent/resources.env
    volumes:
      - ./agent:/home/jovyan/work
      - ${HOME}/.aws:/home/jovyan/.aws
    ports:
      - 8888:8888
    working_dir: /home/jovyan
    entrypoint: [start.sh]
    command: [jupyter, lab, --LabApp.token='']
