version: '2.4'

services:
  default:
    build: .
    image: pytorch-notebook
    container_name: neural-style-transfer
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
    command: [start.sh, jupyter, lab, --LabApp.token='']
