version: '2.4'

services:
  default:
    build:
      context: agent
      dockerfile: Dockerfile
    image: neural-style-transfer-agent
    container_name: neural-style-transfer-agent
    volumes:
      - ./agent:/home/jovyan/work
    ports:
      - 8888:8888
    command: [start.sh, jupyter, lab, --LabApp.token='']
