AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Environment:
    Type: String
    AllowedValues:
      - development
      - production
      - staging
      - testing


Resources:

  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/vpc.yml
      Parameters:
        Environment: !Ref Environment

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/load-balancer.yml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt Vpc.Outputs.VpcId
        SubnetIds: !GetAtt Vpc.Outputs.PublicSubnetIds

  RedisCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/redis-cluster.yml
      Parameters:
        Environment: !Ref Environment
        SubnetIds: !GetAtt Vpc.Outputs.PrivateSubnetIds
        VpcId: !GetAtt Vpc.Outputs.VpcId

  ImageBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/image-bucket.yml
      Parameters:
        Environment: !Ref Environment

  AgentBatchJob:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/agent-batch-job.yml
      Parameters:
        Environment: !Ref Environment
        ImageBucketName: !GetAtt ImageBucket.Outputs.S3BucketName
        SubnetIds: !GetAtt Vpc.Outputs.PrivateSubnetIds
        VpcId: !GetAtt Vpc.Outputs.VpcId

  ServerCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/server-cluster.yml
      Parameters:
        BatchJobDoneQueueArn: !GetAtt AgentBatchJob.Outputs.DoneQueueArn
        BatchJobDoneQueueUrl: !GetAtt AgentBatchJob.Outputs.DoneQueueUrl
        BatchJobStartDefinitionArn: !GetAtt AgentBatchJob.Outputs.JobDefinitionArn
        BatchJobStartQueueArn: !GetAtt AgentBatchJob.Outputs.StartQueueArn
        Environment: !Ref Environment
        ImageBucketName: !GetAtt ImageBucket.Outputs.S3BucketName
        ImageBucketUrl: !GetAtt ImageBucket.Outputs.S3BucketUrl
        LoadBalancerListenerArn: !GetAtt LoadBalancer.Outputs.ListenerArn
        LoadBalancerSecurityGroupId: !GetAtt LoadBalancer.Outputs.SecurityGroupId
        RedisClusterEndpoint: !GetAtt RedisCluster.Outputs.Endpoint
        RedisClusterSecurityGroupId: !GetAtt RedisCluster.Outputs.SecurityGroupId
        SubnetIds: !GetAtt Vpc.Outputs.PrivateSubnetIds
        VpcId: !GetAtt Vpc.Outputs.VpcId
