export const DISCONNECTED = 'disconnect';
export const LIST_IMAGES = 'LIST_IMAGES';
export const TRANSFER_STYLE = 'TRANSFER_STYLE';
export const TRANSFER_STYLE_COMPLETED = 'TRANSFER_STYLE_COMPLETED';

export default {
  DISCONNECTED,
  LIST_IMAGES,
  TRANSFER_STYLE,
  TRANSFER_STYLE_COMPLETED,
}
